### ISSUE TITLE
移植完成

### ISSUE THREAD

**Issue by wwwying9** [SummerFalls/UDS_S32K144_APP#2]
按照这份示例，完成了移植，感谢！ 
另外想问下是否有应用层TDC相关的示例参考。

**Comment by wwwying9** [comment]
DTC

**Comment by SummerFalls** [comment]
@wwwying9 刚刚 MCU 端的 3个工程 Release 了新版本，重新移植吧，修复了之前版本的很多问题。

:game_die: 目前已做通用性适配，目前一套代码理论同时支持多个型号，已测试 `S32K144` 和 `S32K118` 可以同时支持，想自行适配其它几个型号只需要自行新建工程即可。

**Comment by SummerFalls** [comment]
DTC 没做，自己找找资料吧~~~

**Comment by wwwying9** [comment]
我用的好好的额。。。。。只是把Flash操作代码放在了ROM中了

你有详细一点点的版本变更记录么？我好去对照查找一下。

要是实在不行只能重新移植了。

**Comment by SummerFalls** [comment]
改动相当多吧，今天再 Release 一版，解决一个关键问题。

**Comment by SummerFalls** [comment]
Release: [v1.2 UDS_S32K144_APP 常规性BUG修复](https://github.com/SummerFalls/UDS_S32K144_APP/releases/tag/v1.2)
Release: [v1.2 UDS_S32K144_Bootloader 常规性BUG修复](https://github.com/SummerFalls/UDS_S32K144_Bootloader/releases/tag/v1.2)
Release: [v1.1 UDS_S32K144_FlashDriver 代码简化](https://github.com/SummerFalls/UDS_S32K144_FlashDriver/releases/tag/v1.1)
